# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheMovie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheMovie

  target 'TheMovieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheMovieUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
